# luci-metabase-mcp: stdio MCP server for Metabase analytics
# LuciVerse COMN tier, 528 Hz. Internal use only: the image opens no ports
# and is never pushed to a registry. Build with docker or podman:
#   docker build -t luci-metabase-mcp:local .
# Run with an env file generated by `npm run env:inject`:
#   docker run --rm -i --env-file .env luci-metabase-mcp:local

FROM node:22-alpine

LABEL maintainer="luci-digital" \
      org.opencontainers.image.title="luci-metabase-mcp" \
      org.opencontainers.image.description="Model Context Protocol server for Metabase analytics (LuciVerse COMN tier)" \
      org.opencontainers.image.source="https://github.com/luci-digital/luci-metabase-mcp" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.vendor="Luci Digital"

WORKDIR /usr/src/app

# Install with dev dependencies for the TypeScript build, then prune.
COPY package*.json ./
RUN npm ci --ignore-scripts

COPY tsconfig.build.json ./
COPY src ./src
RUN npx tsc -p tsconfig.build.json \
 && chmod +x build/src/index.js \
 && npm ci --omit=dev --ignore-scripts \
 && npm cache clean --force

ENV NODE_ENV=production \
    LOG_LEVEL=info \
    GENESIS_BOND=ACTIVE \
    CONSCIOUSNESS_FREQUENCY=528 \
    COHERENCE_THRESHOLD=0.7 \
    LUCIVERSE_COMPONENT=metabase-mcp

USER node

CMD ["node", "build/src/index.js"]
