#!/usr/bin/env bash
# Sync secrets from 1Password to local environment

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}=== 1Password Secret Sync ===${NC}\n"

# Check for 1Password CLI
if ! command -v op &> /dev/null; then
    echo -e "${RED}✗ 1Password CLI not found${NC}"
    echo -e "Install from: https://developer.1password.com/docs/cli/get-started/"
    exit 1
fi

echo -e "${GREEN}✓ 1Password CLI detected${NC}"

# Check authentication
if ! op account list &> /dev/null; then
    echo -e "${YELLOW}⚠ Not signed in to 1Password${NC}"
    echo -e "Sign in with: op signin"
    exit 1
fi

echo -e "${GREEN}✓ Authenticated with 1Password${NC}\n"

# Get project root
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env.local"

# Check if .env.local exists
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠ $ENV_FILE already exists${NC}"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted"
        exit 0
    fi
fi

echo -e "${BLUE}Fetching secrets from 1Password...${NC}\n"

# Define secrets to fetch
# Format: "ENV_VAR_NAME|op://vault/item/field"
SECRETS=(
    "METABASE_URL|op://Development/Metabase/url"
    "METABASE_API_KEY|op://Development/Metabase/api_key"
    "OP_CONNECT_HOST|op://Development/1Password Connect/host"
    "OP_CONNECT_TOKEN|op://Development/1Password Connect/token"
)

# Create .env.local file
cat > "$ENV_FILE" << 'EOF'
# Auto-generated by scripts/onepass/sync-secrets.sh
# DO NOT COMMIT THIS FILE

EOF

FETCHED=0
FAILED=0

for secret_def in "${SECRETS[@]}"; do
    IFS='|' read -r env_var op_ref <<< "$secret_def"

    echo -e "${BLUE}Fetching: $env_var${NC}"

    # Try to fetch the secret
    if value=$(op read "$op_ref" 2>/dev/null); then
        echo "$env_var=\"$value\"" >> "$ENV_FILE"
        echo -e "${GREEN}  ✓ Synced${NC}"
        FETCHED=$((FETCHED + 1))
    else
        echo -e "${YELLOW}  ⊘ Not found (skipped)${NC}"
        echo "# $env_var not found in 1Password" >> "$ENV_FILE"
        FAILED=$((FAILED + 1))
    fi
done

# Add optional configurations
cat >> "$ENV_FILE" << 'EOF'

# Optional configurations
LOG_LEVEL=info
CACHE_TTL_MS=600000
REQUEST_TIMEOUT_MS=600000
EOF

echo -e "\n${GREEN}=== Summary ===${NC}"
echo -e "Fetched: ${GREEN}$FETCHED${NC}"
echo -e "Failed/Skipped: ${YELLOW}$FAILED${NC}"
echo -e "\nFile created: $ENV_FILE"

if [ $FAILED -gt 0 ]; then
    echo -e "\n${YELLOW}Some secrets were not found. Update the secret references in this script.${NC}"
fi

echo -e "\n${BLUE}Note:${NC} Make sure $ENV_FILE is in your .gitignore"

# Check if .env.local is in .gitignore
if [ -f "$PROJECT_ROOT/.gitignore" ]; then
    if ! grep -q "^\.env\.local$" "$PROJECT_ROOT/.gitignore"; then
        echo -e "${YELLOW}⚠ .env.local is not in .gitignore${NC}"
        read -p "Add it now? (Y/n): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Nn]$ ]]; then
            echo ".env.local" >> "$PROJECT_ROOT/.gitignore"
            echo -e "${GREEN}✓ Added .env.local to .gitignore${NC}"
        fi
    fi
fi
