#!/usr/bin/env bash
# Validate that no secrets are being committed.
#
# 1Password secret references (op://vault/item/field) are pointers, not
# secrets, and are allowed. Documented placeholders in .env.example are
# allowed. Everything else that looks like a credential blocks the commit.

set -euo pipefail

echo "[validate-secrets] Checking staged files..."

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

if [ -z "$STAGED_FILES" ]; then
    echo "[ok] No files staged"
    exit 0
fi

# Lines matching this filter are ignored before pattern matching.
IGNORE_FILTER='op://|your_|example\.com|REPLACE_ME|\$\{[A-Za-z_]+\}'

PATTERNS=(
    "OP_CONNECT_TOKEN=['\"]?[A-Za-z0-9_-]{40,}['\"]?"
    "OP_SERVICE_ACCOUNT_TOKEN=['\"]?[A-Za-z0-9_-]{40,}"
    "METABASE_API_KEY=['\"]?[A-Za-z0-9_-]{32,}['\"]?"
    "METABASE_PASSWORD=['\"]?[^'\"[:space:]]{8,}['\"]?"
    "password['\"]?[[:space:]]*[:=][[:space:]]*['\"]?[^'\"[:space:]]{8,}['\"]?"
    "['\"]?[A-Za-z0-9_-]{32,}['\"]?[[:space:]]*#.*[Aa][Pp][Ii].*[Kk]ey"
    "Bearer [A-Za-z0-9_-]{32,}"
    "ghp_[A-Za-z0-9]{36,}"
    "gho_[A-Za-z0-9]{36,}"
    "AKIA[0-9A-Z]{16}"
    "['\"]?aws_secret_access_key['\"]?[[:space:]]*[:=]"
    "-----BEGIN [A-Z]+ PRIVATE KEY-----"
)

# Files that are never allowed to be committed (exact basename match).
ALWAYS_BLOCK=(
    ".env"
    ".env.local"
    ".env.production"
    "credentials.json"
    "secrets.json"
)

ISSUES_FOUND=0
SUSPICIOUS_FILES=()

for file in $STAGED_FILES; do
    if [ ! -f "$file" ]; then
        continue
    fi

    base="$(basename "$file")"

    case "$base" in
        .env.example|.env.template)
            # Documented templates are allowed; still scanned below.
            ;;
        *)
            for blocked in "${ALWAYS_BLOCK[@]}"; do
                if [[ "$base" == "$blocked" ]]; then
                    echo "[fail] Sensitive file staged: $file"
                    SUSPICIOUS_FILES+=("$file")
                    ISSUES_FOUND=$((ISSUES_FOUND + 1))
                    break
                fi
            done
            ;;
    esac

    for pattern in "${PATTERNS[@]}"; do
        if grep -vE "$IGNORE_FILTER" "$file" | grep -qE "$pattern" 2>/dev/null; then
            MATCHES=$(grep -vE "$IGNORE_FILTER" "$file" | grep -nE "$pattern" | head -5)
            echo "[fail] Potential secret in: $file"
            echo "       Pattern: $pattern"
            echo "$MATCHES" | while read -r line; do
                echo "       $line"
            done
            SUSPICIOUS_FILES+=("$file")
            ISSUES_FOUND=$((ISSUES_FOUND + 1))
            break
        fi
    done
done

if [ "$ISSUES_FOUND" -eq 0 ]; then
    echo "[ok] No secrets detected"
    exit 0
fi

echo "[fail] Secret validation failed: $ISSUES_FOUND potential issue(s)"
echo "Suspicious files:"
for file in "${SUSPICIOUS_FILES[@]}"; do
    echo "  - $file"
done
echo ""
echo "What to do:"
echo "  1. Remove the secret from the file"
echo "  2. Use a 1Password reference instead: op://vault/item/field"
echo "  3. Keep real values in .env (git-ignored), generated by: npm run env:inject"
echo "If you are certain these are not secrets: git commit --no-verify"
exit 1
